version: '3.8'

services:
  ospy:
    build: .
    container_name: ospy-monitor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./configs/config.yaml:/app/configs/config.yaml:ro
    environment:
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    networks:
      - ospy-network
    healthcheck:
      test: ["CMD", "./ospy", "-version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ospy-network:
    driver: bridge

volumes:
  ospy-data:
  ospy-logs:
