monitoring:
  interval: 30s        # Check every 30 seconds
  timeout: 10s         # Request timeout
  retries: 3           # Number of retries
  workers: 5           # Concurrent workers

# Websites to monitor
websites:
  - name: "Google"
    url: "https://google.com"
    method: "GET"
    expected_status: 200
    
  - name: "GitHub"
    url: "https://github.com"
    method: "GET"
    expected_status: 200

# Notification settings
notifications:
  email:
    enabled: true
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    from: "ospy-alerts@gmail.com"
    to: ["rvikntchuhn@gmail.com"]
    
  telegram:
    enabled: true
    bot_token: ""
    chat_id: ""

# Storage configuration
storage:
  type: "sqlite"
  path: "./data/ospy.db"
  retention_days: 30

# Web interface
web:
  enabled: true
  host: "0.0.0.0"
  port: 8080

# Logging
logging:
  level: "info"
  file: "./logs/ospy.log"
  max_size: 100
  max_backups: 5
